spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangosteen_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mangosteen
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888

jwt:
  secret: uDdC9SbuVKip3ijiltVsR9X69l+J5EfvKVJMA4MTfbs=

logging:
  level:
    com.mangosteen.app: DEBUG

pagehelper:
  debug: true
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
