spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangosteen_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mangosteen
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888